### NumPy Basics Homework Assignment ###

**Instructions**: As usual, make a Jupyter Notebook and do the homework in that. Also, the [NumPy beginner's guide](https://numpy.org/doc/stable/user/absolute_beginners.html) is quite good, so make friends with it.

1. **Array Creation**:

a. Create a 1D array containing numbers from 0 to 9.

In [17]:
import numpy as np
num_array = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
num_array

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

b. Create a 3x3 matrix with numbers from 1 to 9.

In [18]:
axis_array = np.array([[1,2,3], [4,5,6], [7,8,9]])
axis_array

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

c. Generate a 1D array of 10 random integers between 50 and 100.

In [19]:
rng = np.random.default_rng()
rand50_100 = rng.integers (50, high = 101, size = 10)
rand50_100

array([71, 77, 92, 95, 52, 61, 63, 75, 97, 80], dtype=int64)

d. Create a 3x4 matrix of random floating-point numbers between 0 and 1.

In [20]:
rand_matrix = rng.random((3,4))
rand_matrix

array([[0.27974388, 0.64003023, 0.91797355, 0.7610832 ],
       [0.84487768, 0.87625638, 0.5596033 , 0.79172185],
       [0.04606297, 0.61470137, 0.82091957, 0.35015056]])

2. **Array Indexing**:

a. From the 1D array created in 1a, extract all even numbers.

In [21]:
num_array[::2]

array([0, 2, 4, 6, 8])

b. From the 3x3 matrix created in 1b, extract the second row.

In [22]:
axis_array[1]

array([4, 5, 6])

c. From the 3x3 matrix, extract the element at the third row and second column.

In [23]:
axis_array[2,1]

8

d. From the 3x4 matrix created in 1d, extract all elements greater than 0.5.

In [24]:
rand_matrix_greater = np.extract(rand_matrix > 0.5, rand_matrix)
rand_matrix_greater

array([0.64003023, 0.91797355, 0.7610832 , 0.84487768, 0.87625638,
       0.5596033 , 0.79172185, 0.61470137, 0.82091957])

3. **Basic Math Operations**:

a. Create two arrays `A` and `B` of shape (4, 4) with random integers between 1 and 10. Compute the element-wise sum and product.

In [25]:
A_one = rng.integers (1, high = 10, size = 4)
A_two = rng.integers (1, high = 10, size = 4)
A_three = rng.integers (1, high = 10, size = 4)
A_four = rng.integers (1, high = 10, size = 4)
array_A = np.array([A_one, A_two, A_three, A_four])
B_one = rng.integers (1, high = 10, size = 4)
B_two = rng.integers (1, high = 10, size = 4)
B_three = rng.integers (1, high = 10, size = 4)
B_four = rng.integers (1, high = 10, size = 4)
array_B = np.array([B_one, B_two, B_three, B_four])
array_A * array_B

array([[35, 12,  4, 27],
       [56, 30, 20, 21],
       [ 7,  2, 14,  8],
       [32,  5, 56, 56]], dtype=int64)

In [26]:
array_A + array_B

array([[12,  8,  4, 12],
       [15, 11,  9, 10],
       [ 8,  3,  9,  6],
       [12,  6, 15, 15]], dtype=int64)

b. Multiply the 1D array created in 1a by 5.

In [27]:
num_array * 5

array([ 0,  5, 10, 15, 20, 25, 30, 35, 40, 45])

c. Subtract the mean of the 1D array created in 1a from each of its elements.

In [28]:
num_array_mean = num_array.mean()
num_array - num_array_mean

array([-4.5, -3.5, -2.5, -1.5, -0.5,  0.5,  1.5,  2.5,  3.5,  4.5])

4. **Basic Statistical Calculations**:

a. Compute the mean, median, and standard deviation of the 1D array from 1a.

In [29]:
num_array_mean = np.mean(num_array)
num_array_median = np.median(num_array)
num_array_std = np.std(num_array)
print("The mean is", num_array_mean)
print("The std is", num_array_std)
print("The median is", num_array_median)

The mean is 4.5
The std is 2.8722813232690143
The median is 4.5


b. Find the minimum and maximum values of the 3x4 matrix created in 1d.

In [30]:
rand_matrix_min = np.min(rand_matrix)
rand_matrix_max = np.max(rand_matrix)
print("The minimum value is", rand_matrix_min)
print("The maximum value is", rand_matrix_max)

The minimum value is 0.04606297454421282
The maximum value is 0.9179735453201819


c. Find the position (index) of the minimum and maximum values in the 1D array created in 1c.

In [31]:
rand50_100_max_index = np.ndarray.argmax(rand50_100)
rand50_100_min_index = np.ndarray.argmin(rand50_100)
print("The maximum value occurs in index position:", rand50_100_max_index)
print("The minimum value occurs in index position:", rand50_100_min_index)

The maximum value occurs in index position: 8
The minimum value occurs in index position: 4


5. **Bonus (Optional)**:

a. Compute the dot product of two 1D arrays of length 5. Remember, the dot product is the sum of the products of corresponding entries of the two sequences of numbers.

In [32]:
array_one = np.array([1, 2, 3, 4, 5])
array_two = np.array([1, 2, 3, 4, 5])
sum((array_one*array_two) + (array_one*array_two))

110

b. Reshape the 3x3 matrix from 1b into a 1D array of length 9.

In [33]:
axis_array.reshape(1,9)

array([[1, 2, 3, 4, 5, 6, 7, 8, 9]])